#cloud-config
users:
  - name: finn-rm
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_import_id:
      - lp:finn-rm

package_update: true
package_upgrade: true

packages:
  - ssh-import-id
  - python3

final_message: "The system is ready for Ansible configuration, after $UPTIME seconds" 