version: '3.8'

services:
  traefik:
    image: traefik:v2.10
    command:
      - "--log.level=INFO"
      - "--accesslog=true"
      - "--accesslog.filepath=/dev/stdout"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.directory=/etc/traefik/dynamic"
      - "--providers.file.watch=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--api.insecure=true"
      - "--api.dashboard=true"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"  # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/dynamic:/etc/traefik/dynamic
    networks:
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.local`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.entrypoints=web"

  registry:
    build:
      context: ./registry
      dockerfile: Dockerfile
    volumes:
      - ./traefik/dynamic:/output
    restart: unless-stopped
    networks:
      - traefik-public
    environment:
      - DOMAIN_BASE=${DOMAIN_BASE:-preview.tafu.casa}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.registry-dashboard.rule=Host(`registry.${DOMAIN_BASE:-preview.tafu.casa}`)"
      - "traefik.http.services.registry-dashboard.loadbalancer.server.port=5000"

networks:
  traefik-public:
    external: true 